# Generated by Django 4.0.5 on 2022-06-23 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='users',
            table='Login',
        ),
    ]
